version: '3.4'
services:

  web.db:
    container_name: web.db
    image: mysql
    ports: 
      - "3380:3306"
    environment:  
      - MYSQL_ROOT_PASSWORD=mysql1234
      - MYSQL_USER=app
      - MYSQL_PASSWORD=mysql1234
      - TZ=Asia/Shanghai
    command: 
      mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    networks: 
      - web_network

  app:
    container_name: app
    build: ./SimpleWeb.NetCore
    expose: 
      - "5000"
    depends_on:
      - web.db
    environment:
      - TZ=Asia/Shanghai
    networks: 
      - web_network
  
  reverse-proxy:
    container_name: server-nginx.proxy
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/usr/share/nginx/html
    networks: 
      - web_network

networks:
  web_network:
    driver: bridge
    
 